#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.kde.k3b.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/k3btheme.knsrc -- "$@"
# End automatically added section
